name = "ZernikeApprox"
uuid = "661048f7-0d18-492d-b41c-b48e600c9b50"
authors = ["Angel M. Ortiz-Ochoa"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
